apiVersion: v2
appVersion: 6.1.0.0.01
dependencies:
- alias: sch
  name: ibm-sch
  version: ^1.2.18
- name: ibm-ssp-engine
  version: 1.3.1
name: ibm-ssp-engine-umbrella
type: application
version: 1.3.1
